import type { Metadata } from "next";
import { Inter } from "next/font/google";
import backGroundHome from "../../public/background-home.svg";
import "./globals.css";
import { NavbarProvider } from "@/contexts/NavbarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavbarProvider>
          {children}
        </NavbarProvider>
      </body>
    </html>
  );
}
