import type { Metadata } from "next";
import { Inter } from "next/font/google";
import backGroundHome from "../../public/background-home.svg";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background-home bg-cover`}>
        {children}
      </body>
    </html>
  );
}
